baseURL = "https://linuxsystem.openinventionnetwork.com"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "OIN Linux System"
theme = "docdock"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
paginate = 10000

[taxonomies]
technology = "Technology Area"
#licenses = "License"
Orig_Prj = "Originating Project"

[params]
showVisitedLinks = false
themeStyle = "original" # "original" or "flex" # default "flex"
themeVariant = "gray" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = true # default is false
disableSearch = false # default is false
disableNavChevron = true # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

# Activate search
[outputs]
home = [ "HTML", "JSON"]

[[menu.shortcuts]]
name = "<i class='fa fa-list-alt'></i> Packages"
identifier = "ds"
url = "/packages/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-list-alt'></i> By Technology Area"
identifier = "ab"
url = "/technology-area/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-list-alt'></i> By Originating Project"
identifier = "li"
url = "/originating-project/"
weight = 25

[[menu.shortcuts]]
name = "<i class='fa fa-list-alt'></i> Table view"
url = "/"
weight = 25


#[[menu.shortcuts]]
#name = "<i class='fa fa-list-alt'></i> By License"
#identifier = "op"
#url = "/license/"
#weight = 30
